### ISSUE TITLE
[BUG] attempting to create file to run to launch server with given chmod command fails

### ISSUE THREAD

**Issue by GeneralWiggin** [Drehmal-Team/installer#2]
**Describe the bug**
Upon completion of server installation, running the given chmod command fails to generate server script executable

**To Reproduce**
1. follow steps to install server on ubuntu linux
2. upon completion, attempt to run the generated chmod command
3. watch command fail, giving error of "chmod: cannot access '/media/<redacted personal name>/gaming/servers/server.sh': No such file or directory"

**Expected behavior**
generation of a server.sh file

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04

**Additional context**
error on terminal is "chmod: cannot access '/media/<redacted personal name>/gaming/servers/server.sh': No such file or directory"

**Log File**
omitting log due to references to my username, which is my irl name, and due to error occuring on command line, not within installer.

**Comment by GeneralWiggin** [comment]
[13-01-2024_1-installer.log](https://github.com/Drehmal-Team/installer/files/13930182/13-01-2024_1-installer.log)


I forgot find and replace exists, have log

**Comment by GeneralWiggin** [comment]
testing on latest version, I notice that the generated commend uses "server.sh" but the file in directory is "run.ch"

**Comment by jgaribsin** [comment]
fixed with v0.2.0: user is no longer required to run a chmod command themself
