### ISSUE TITLE
[BUG] Resource pack fails to download on multiplayer option for ubuntu

### ISSUE THREAD

**Issue by GeneralWiggin** [Drehmal-Team/installer#4]
**Describe the bug**
After selecting the download resource pack button in the multiplayer install screen, it sits at 0.0% and instantly generates an error in the log.

**To Reproduce**
1. Select multiplayer install
2. select any ram amount
3. click download button for resource pack.

**Expected behavior**
Resource pack should download and install properly.

**Screenshots**
![image](https://github.com/Drehmal-Team/installer/assets/46917052/4c7da308-2ea2-4536-ae8b-378f4b77fb3c)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04

**Additional context**
Install attempts performed on a machine with prior drehmal manual installations.

**Log File**
[14-01-2024_1-installer.log](https://github.com/Drehmal-Team/installer/files/13932852/14-01-2024_1-installer.log)

**Comment by GeneralWiggin** [comment]
this bug also occurs when attempting singleplayer install on same OS.

**Comment by s0ph0s-2** [comment]
It also fails on macOS 14.2.1 in an identical way.

**Comment by jgaribsin** [comment]
Thanks for the report! This should be fixed with commit [fd6cfda](https://github.com/Drehmal-Team/installer/commit/fd6cfdad6b7db8fea6d58123cc83072c3629bf6e) / version [v0.1.1](https://github.com/Drehmal-Team/installer/releases/tag/v0.1.1).
