### ISSUE TITLE
[BUG] CEM not included in mods installed by the installer.

### ISSUE THREAD

**Issue by fan-of123** [Drehmal-Team/installer#5]
Multiple mods included on the mod list are not installed by the installer, notably CEM, but also: LazyDFU, Starlight, and WI Zoom. CEM specifically is definitely needed.

**To Reproduce**
Run the installer, click "Download mods"

**Expected behavior**
CEM should be one of the mods installed by the installer.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I'm on installer 0.3.0.

**Log File**
[18-02-2024-installer.log](https://github.com/Drehmal-Team/installer/files/14321272/18-02-2024-installer.log)

**Comment by jgaribsin** [comment]
fixed with 89798104018ae4eee5e2b2a521a73f52463bb0b4
