### ISSUE TITLE
[BUG] CIT as installed by the installer w/out any modified settings doesn't work.

### ISSUE THREAD

**Issue by fan-of123** [Drehmal-Team/installer#6]
**Describe the bug**
Running the installer normally without editing any of the file paths breaks CIT Resewn. The game sends a java.io.FileNotFoundException (I included the log file as part of the report)

**To Reproduce**
1. Download and run the installer without changing the filepaths.
2. Open the game.

**Expected behavior**
CIT needs to work to pass the chestplate test, and for a lot of textures to work.

**Screenshots**
![image](https://github.com/Drehmal-Team/installer/assets/87401247/764f955e-7827-4dd2-9b58-960307822575)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
This is my first time running the installer. Version: 0.3.0

**Log File**
Your log file, located at one of the following locations:
[latest.log](https://github.com/Drehmal-Team/installer/files/14321297/latest.log)
[18-02-2024-installer.log](https://github.com/Drehmal-Team/installer/files/14321298/18-02-2024-installer.log)

**Comment by jgaribsin** [comment]
fixed with commit 89798104018ae4eee5e2b2a521a73f52463bb0b4
